# =============================================================================
# StmCorpusBuild.R
# Build the corpus for STM for LLM-generated explanations
# Requires objects from grade_mc_responses.R and readDOCX-AllModels.R
# =============================================================================

library(dplyr)
library(stringr)
library(readr)
library(stm)
library(tidytext)
library(tidyr)

# -----------------------------------------------------------------------------
# 1. scored_responses_long.csv generated by grade_mc_responses.R
# -----------------------------------------------------------------------------

scored_long <- read_csv("scored_responses_long.csv")

# -----------------------------------------------------------------------------
# 2. Load explanation text
# -----------------------------------------------------------------------------
# all_explanations_long.csv generated with readDOCX-AllModels.R
# Must contain: Question, Exam, Model, explanation_text

explanations_long <- read_csv("all_explanations_long.csv")

# -----------------------------------------------------------------------------
# 3. Create Model crosswalk because model names differ between 
# scored_long and explanations_long
# -----------------------------------------------------------------------------

model_crosswalk <- tibble::tribble(
  ~model_folder,                    ~Model_accuracy,
  "claude-3-7-sonnet",              "Claude37",
  "claude-sonnet-4",                "Claude4",
  "claude-sonnet-4-6",              "Claude46",
  "gemini-2.0-flash-lite",          "Gemini20",
  "gemini-2.5-flash-lite",          "Gemini25",
  "gemini-3.1-flash-lite-preview",  "Gemini31",
  "gpt-4o",                         "GPT4o",
  "gpt-5",                          "GPT5",
  "gpt-5-4",                        "GPT54",
  "gpt-5.1",                        "GPT51",
  "gpt-5.4-mini",                   "GPT54-mini",
  "gpt-5.4-nano",                   "GPT54-nano",
  "grok-2-vision",                  "Grok2-vision",
  "grok-4-1",                       "Grok41",
  "grok-4.3",                       "Grok43"
)
# -----------------------------------------------------------------------------
# 3. Merge explanations with accuracy metadata
# -----------------------------------------------------------------------------

stm_meta <- all_explanations %>%
  left_join(model_crosswalk, by = "model_folder") %>%
  left_join(
    scored_long %>%
      mutate(
        Question = as.numeric(Question),
        Exam = as.character(Exam),
        Model_accuracy = as.character(Model)
      ) %>%
      select(
        Question,
        Exam,
        Model_accuracy,
        Truth,
        Response,
        Response_clean,
        Score
      ),
    by = c("Question", "Exam", "Model_accuracy")
  ) %>%
  mutate(
    Model = factor(model_folder),
    Exam = factor(Exam, levels = c("ACTM", "AP", "CAOS", "GE")),
    qtype = factor(qtype, levels = c("MC", "SA")),
    image = factor(image, levels = c("No image", "Image")),
    correct = case_when(
      qtype == "SA" ~ "Not scored",
      Exam == "AP" ~ "Not scored",
      Score == 1 ~ "Correct",
      Score == 0 ~ "Incorrect",
      TRUE ~ "Not scored"
    ),
    correct = factor(correct, levels = c("Incorrect", "Correct", "Not scored"))
  )

# Create three types of "not scored" questions
stm_meta <- stm_meta %>%
  mutate(
    MC_Response_Type = case_when(
      qtype == "MC" & Response_clean == "NC" ~ "No conclusion",
      qtype == "MC" & Response_clean == "NA_RESP" ~ "No response",
      qtype == "MC" & Score == 1 ~ "Correct",
      qtype == "MC" & Score == 0 ~ "Incorrect",
      TRUE ~ NA_character_
    ),
    MC_Response_Type = factor(
      MC_Response_Type,
      levels = c(
        "Correct",
        "Incorrect",
        "No conclusion",
        "No response"
      )
    )
  )
# -----------------------------------------------------------------------------
# 4. Sanity Checks
# -----------------------------------------------------------------------------

stm_meta %>%
  count(qtype, MC_Response_Type)

stm_meta %>%
  filter(qtype == "MC") %>%
  count(MC_Response_Type)

stm_meta %>%
  filter(qtype == "MC") %>%
  count(Model_accuracy, MC_Response_Type) %>%
  group_by(Model_accuracy) %>%
  mutate(percent = round(100 * n / sum(n), 1)) %>%
  ungroup()

# -----------------------------------------------------------------------------
# 5. Compute response summary
# -----------------------------------------------------------------------------

response_summary <- stm_meta %>%
  filter(qtype == "MC") %>%
  count(Model_accuracy, MC_Response_Type) %>%
  group_by(Model_accuracy) %>%
  mutate(
    Percent = round(100 * n / sum(n), 1)
  ) %>%
  tidyr::pivot_wider(
    names_from = MC_Response_Type,
    values_from = c(n, Percent),
    values_fill = 0
  ) %>%
  ungroup()

## Nice tables from response_summary
library(knitr)
library(kableExtra)

response_table <- response_summary %>%
  transmute(
    Model = Model_accuracy,
    `Correct (%)` = Percent_Correct,
    `Incorrect (%)` = Percent_Incorrect,
    `No conclusion (%)` = `Percent_No conclusion`,
    `No response (%)` = `Percent_No response`
  ) %>%
  arrange(desc(`Correct (%)`))

# Percentages only
response_table %>%
  kable(
    format = "latex",
    booktabs = TRUE,
    digits = 1,
    caption = "Multiple-choice response behavior by model.",
    label = "tab:response_behavior"
  ) %>%
  kable_styling(latex_options = c("hold_position"))

# Counts and percentages
response_table_counts <- response_summary %>%
  transmute(
    Model = Model_accuracy,
    Correct = paste0(n_Correct, " (", Percent_Correct, "\\%)"),
    Incorrect = paste0(n_Incorrect, " (", Percent_Incorrect, "\\%)"),
    `No conclusion` = paste0(`n_No conclusion`, " (", `Percent_No conclusion`, "\\%)"),
    `No response` = paste0(`n_No response`, " (", `Percent_No response`, "\\%)")
  ) %>%
  arrange(desc(parse_number(Correct)))

# =============================================================================
# 5. Clean explanation text before STM
# =============================================================================
clean_explanation_text <- function(x) {
  x %>%
    # normalize line endings
    str_replace_all("\r\n|\r", "\n") %>%
    
    # remove markdown headings
    str_replace_all("(?m)^#+\\s*", " ") %>%
    
    # remove common boilerplate headings
    str_replace_all("(?i)multiple choice question response", " ") %>%
    str_replace_all("(?i)short answer question response", " ") %>%
    str_replace_all("(?i)final answer", " ") %>%
    str_replace_all("(?i)answer:", " ") %>%
    str_replace_all("(?i)explanation:", " ") %>%
    str_replace_all("(?i)reasoning:", " ") %>%
    str_replace_all("(?i)solution:", " ") %>%
    
    # remove common LLM filler phrases
    str_replace_all("(?i)let'?s solve this step by step", " ") %>%
    str_replace_all("(?i)let me work through this", " ") %>%
    str_replace_all("(?i)we need to determine", " ") %>%
    str_replace_all("(?i)the correct answer is", " ") %>%
    str_replace_all("(?i)therefore,? the answer is", " ") %>%
    str_replace_all("(?i)thus,? the answer is", " ") %>%
    
    # remove isolated answer-choice declarations
    str_replace_all("(?i)\\boption\\s+[a-e]\\b", " ") %>%
    str_replace_all("(?i)\\bchoice\\s+[a-e]\\b", " ") %>%
    str_replace_all("(?i)\\banswer\\s+[a-e]\\b", " ") %>%
    
    # remove markdown bullets and numbering artifacts
    str_replace_all("(?m)^\\s*[-*+]\\s+", " ") %>%
    str_replace_all("(?m)^\\s*\\d+\\.\\s+", " ") %>%
    
    # remove markdown emphasis/backticks
    str_replace_all("[`*_]", " ") %>%
    
    # remove URLs, if any
    str_replace_all("https?://\\S+|www\\.\\S+", " ") %>%
    
    # normalize whitespace
    str_replace_all("\\s+", " ") %>%
    str_squish()
}

stm_meta <- stm_meta %>%
  mutate(
    explanation_clean = clean_explanation_text(explanation_text),
    n_words_raw = str_count(explanation_text, "\\S+"),
    n_words_clean = str_count(explanation_clean, "\\S+")
  )

# Check that the cleaning did not remove too much.
stm_meta %>%
  summarise(
    n_docs = n(),
    n_empty_clean = sum(explanation_clean == "" | is.na(explanation_clean)),
    mean_words_raw = mean(n_words_raw),
    mean_words_clean = mean(n_words_clean),
    median_words_raw = median(n_words_raw),
    median_words_clean = median(n_words_clean)
  )

# Inspect a few examples
stm_meta %>%
  select(Model, Exam, Question, qtype, explanation_text, explanation_clean) %>%
  slice_sample(n = 5)

# Frequent word check
top_words <- stm_meta %>%
  select(doc_id = file_name, explanation_clean) %>%
  unnest_tokens(word, explanation_clean) %>%
  count(word, sort = TRUE)

top_words %>%
  print(n = 50)

## Remove some more artifacts
stm_meta <- stm_meta %>%
  mutate(
    explanation_clean = explanation_clean %>%
      str_replace_all("[“”‘’]", "'") %>%
      str_replace_all("\\b\\w*'ll\\b", " ") %>%
      str_replace_all("\\b\\w*n't\\b", " not ") %>%
      str_replace_all("(?<=\\s)-(?=\\w)", " ") %>%
      str_replace_all("\\s+", " ") %>%
      str_squish()
  )


# custom stopwords
custom_stopwords <- c(
  "a", "b", "c", "d", "e",
  "frac",
  "we", "i",
  "this", "would",
  "also", "alreadi", "alright"
)

# STM preprocessing

processed <- textProcessor(
  documents = stm_meta$explanation_clean,
  metadata  = stm_meta,
  lowercase = TRUE,
  removestopwords = TRUE,
  customstopwords = custom_stopwords,
  removenumbers = TRUE,
  removepunctuation = TRUE,
  stem = TRUE,
  wordLengths = c(3, Inf)
)

out <- prepDocuments(
  documents = processed$documents,
  vocab     = processed$vocab,
  meta      = processed$meta,
  lower.thresh = 5
)

docs  <- out$documents
vocab <- out$vocab
meta  <- out$meta

length(docs)
length(vocab)
nrow(meta)

head(vocab, 50)

## Search K
set.seed(2026)

k_result <- searchK(
  documents = docs,
  vocab = vocab,
  K = c(12, 14, 16, 18, 20, 22),
  prevalence = ~ Model + Exam + qtype + image,
  data = meta,
  init.type = "Spectral"
)

plot(k_result)

## Inspect a couple of reasonable values of K
set.seed(2026)

stm16 <- stm(
  documents = docs,
  vocab = vocab,
  K = 16,
  prevalence = ~ Model + Exam + qtype + image,
  data = meta,
  init.type = "Spectral",
  max.em.its = 100
)

stm20 <- stm(
  documents = docs,
  vocab = vocab,
  K = 20,
  prevalence = ~ Model + Exam + qtype + image,
  data = meta,
  init.type = "Spectral",
  max.em.its = 100
)

stm22 <- stm(
  documents = docs,
  vocab = vocab,
  K = 22,
  prevalence = ~ Model + Exam + qtype + image,
  data = meta,
  init.type = "Spectral",
  max.em.its = 100
)

labelTopics(stm16, n = 10)
labelTopics(stm20, n = 10)
labelTopics(stm22, n = 10)

# =============================================================================
# Inspect STM topics: probability words, FREX words, and representative documents
# =============================================================================

library(tibble)
library(purrr)

K_final <- 20 ## Decided on K = 20 after inspecting topics.

# -----------------------------------------------------------------------------
# 1. Highest probability and FREX words
# -----------------------------------------------------------------------------

topic_labels20 <- labelTopics(stm20, n = 12)

topic_word_table <- tibble(
  Topic = 1:K_final,
  Highest_Prob = apply(topic_labels20$prob, 1, paste, collapse = ", "),
  FREX = apply(topic_labels20$frex, 1, paste, collapse = ", "),
  Lift = apply(topic_labels20$lift, 1, paste, collapse = ", "),
  Score = apply(topic_labels20$score, 1, paste, collapse = ", ")
)

print(topic_word_table, n = K_final)

# -----------------------------------------------------------------------------
# 2. Representative documents
# -----------------------------------------------------------------------------

thoughts20 <- findThoughts(
  stm20,
  texts = meta$explanation_clean,
  n = 3
)

# -----------------------------------------------------------------------------
# 3. Convert representative documents into a tidy table
# -----------------------------------------------------------------------------

representative_docs20 <- map_dfr(
  1:K_final,
  function(k) {
    
    docs_k <- thoughts20$docs[[k]]
    
    tibble(
      Topic = k,
      Representative_Doc = seq_along(docs_k),
      Text = docs_k
    )
  }
)

representative_docs20 <- representative_docs20 %>%
  mutate(
    Text_short = str_trunc(Text, width = 500)
  )

print(representative_docs20, n = 60)

# -----------------------------------------------------------------------------
# 4. Helper function to inspect a single topic
# -----------------------------------------------------------------------------

inspect_topic <- function(topic_num, n_chars = 1000) {
  
  cat("\n============================================================\n")
  cat("Topic", topic_num, "\n")
  cat("============================================================\n\n")
  
  cat("Highest probability words:\n")
  cat(topic_word_table$Highest_Prob[topic_num], "\n\n")
  
  cat("FREX words:\n")
  cat(topic_word_table$FREX[topic_num], "\n\n")
  
  cat("Representative documents:\n\n")
  
  representative_docs20 %>%
    filter(Topic == topic_num) %>%
    mutate(Text_display = str_trunc(Text, n_chars)) %>%
    pull(Text_display) %>%
    walk2(
      seq_along(.),
      ~ cat("Document", .y, ":\n", .x, "\n\n")
    )
}

inspect_topic(1)
inspect_topic(15)
inspect_topic(20)

# -----------------------------------------------------------------------------
# 5. Write topic inspection output to a text file
# -----------------------------------------------------------------------------

sink("stm20_topic_inspection.txt")

for (k in 1:K_final) {
  inspect_topic(k, n_chars = 1500)
}

sink()

topic_review_table <- topic_word_table %>%
  left_join(
    representative_docs20 %>%
      group_by(Topic) %>%
      summarise(
        Example_1 = Text_short[1],
        Example_2 = Text_short[2],
        Example_3 = Text_short[3],
        .groups = "drop"
      ),
    by = "Topic"
  ) %>%
  mutate(
    Proposed_Label = ""
  )

write.csv(topic_review_table, "stm20_topic_review_table.csv", row.names = FALSE)

## Save topic labels
topic_labels <- c(
  "Robust Estimation and Resistant Methods",
  "Sampling Bias and Generalizability",
  "Diagnostic Testing and Classification Errors",
  "Regression Design and Experimental Planning",
  "Regression Model Interpretation",
  "Comparing Groups with Randomized Studies",
  "Sampling Distributions and Standardization",
  "Reasoning with Incomplete Information",
  "Procedural Statistical Computation",
  "Probability Modeling and Simulation",
  "Sample Size, Precision, and Margin of Error",
  "Distribution Summaries and Boxplot Interpretation",
  "Correlation and Scatterplot Interpretation",
  "Distribution Shape and Histogram Interpretation",
  "Hypothesis Testing and Statistical Decision Making",
  "Association in Contingency Tables",
  "Confidence Interval Interpretation",
  "Sample Size and Proportion Inference",
  "Randomization and Causal Inference",
  "Discrete Probability Distributions"
)

names(topic_labels) <- 1:20

# Short labels for graphics
topic_labels_short <- c(
  "Robust Methods",
  "Sampling Bias",
  "Diagnostic Testing",
  "Regression Design",
  "Regression Models",
  "Group Comparisons",
  "Sampling Distributions",
  "Incomplete Information",
  "Statistical Computation",
  "Probability Models",
  "Precision & MOE",
  "Distribution Summaries",
  "Correlation",
  "Distribution Shape",
  "Hypothesis Testing",
  "Contingency Tables",
  "Confidence Intervals",
  "Proportion Inference",
  "Causal Inference",
  "Discrete Probability"
)

names(topic_labels_short) <- 1:20

####### Assign questions to dominant topic

theta <- as.data.frame(stm20$theta)
colnames(theta) <- paste0("Topic_", 1:ncol(theta))
topic_question <- bind_cols(meta, theta)

# Produce one row per exam question, with the average topic 
# proportion across the 15 models.
question_topics <- topic_question %>%
  group_by(Exam, Question) %>%
  summarise(
    across(starts_with("Topic_"), mean),
    .groups = "drop"
  )

# Find which topic is most associated with each question
question_topics <- topic_question %>%
  group_by(Exam, Question) %>%
  summarise(
    across(starts_with("Topic_"), mean),
    .groups = "drop"
  ) %>%
  rowwise() %>%
  mutate(
    DominantTopic = which.max(c_across(starts_with("Topic_"))),
    DominantLabel = topic_labels[DominantTopic],
    DominantProb = max(c_across(starts_with("Topic_")))
  ) %>%
  ungroup()

# For each topic, which questions have an average topic 
# probability greater than 0.20?

# Create long format
question_topics_long <- question_topics %>%
  select(Exam, Question, starts_with("Topic_")) %>%
  pivot_longer(
    cols = starts_with("Topic_"),
    names_to = "Topic",
    values_to = "Mean_Probability"
  ) %>%
  mutate(
    Topic = as.integer(gsub("Topic_", "", Topic)),
    Topic_Label = topic_labels[Topic]
  )

# threshold questions 
topic_questions_25 <- question_topics_long %>%
  filter(Mean_Probability >= 0.25) %>%
  arrange(Topic, desc(Mean_Probability))

topic_validation_25 <- topic_questions_25 %>%
  group_by(Topic, Topic_Label) %>%
  summarise(
    N_questions = n(),
    N_exams = n_distinct(Exam),
    Exams = paste(sort(unique(as.character(Exam))), collapse = ", "),
    Questions = paste(
      paste0(as.character(Exam), "-", Question),
      collapse = "; "
    ),
    .groups = "drop"
  )

print(topic_validation_25, n = Inf)
# Create summary table
topic_validation <- topic_questions_20 %>%
  group_by(Topic, Topic_Label) %>%
  summarise(
    N_questions = n(),
    Exams = paste(sort(unique(Exam)), collapse = ", "),
    Questions = paste(
      paste0(Exam, "-", Question),
      collapse = "; "
    ),
    .groups = "drop"
  )

print(topic_validation, n = Inf)

# To avoid thresholding, pick the top 5 questions per topic
top_questions_per_topic <- question_topics_long %>%
  group_by(Topic, Topic_Label) %>%
  slice_max(
    Mean_Probability,
    n = 5,
    with_ties = FALSE
  ) %>%
  arrange(Topic, desc(Mean_Probability))

print(top_questions_per_topic, n = Inf)

write.csv(topic_validation_25,
          "topic_validation_questions_threshold_25.csv",
          row.names = FALSE)

# =============================================================================
# estimateEffect analyses for primary STM
# Start with the primary all-document STM
# =============================================================================

K_final <- 20

topic_effects20 <- estimateEffect(
  1:K_final ~ Model + Exam + qtype + image,
  stmobj = stm20,
  metadata = meta,
  uncertainty = "Global"
)

summary(topic_effects20)
saveRDS(topic_effects20, "topic_effects20_primary.rds")

# Model plot for selected topics
plot(
  topic_effects20,
  covariate = "Model",
  topics = c(15, 17, 19),
  model = stm20,
  method = "pointestimate",
  xlab = "Model",
  ylab = "Expected topic prevalence"
)

# Document-topic proportions
theta20 <- as.data.frame(stm20$theta)
colnames(theta20) <- paste0("Topic_", 1:K_final)

stm_doc_topics <- bind_cols(meta, theta20)

# Average topic prevalence by model
topic_by_model <- stm_doc_topics %>%
  group_by(Model) %>%
  summarise(
    across(starts_with("Topic_"), mean),
    .groups = "drop"
  ) %>%
  tidyr::pivot_longer(
    cols = starts_with("Topic_"),
    names_to = "Topic",
    values_to = "Mean_Prevalence"
  ) %>%
  mutate(
    Topic_Num = as.integer(gsub("Topic_", "", Topic)),
    Topic_Label = topic_labels_short[Topic_Num]
  )

# Inspect strongest model-topic associations
topic_by_model %>%
  group_by(Topic_Num, Topic_Label) %>%
  slice_max(Mean_Prevalence, n = 3, with_ties = FALSE) %>%
  arrange(Topic_Num, desc(Mean_Prevalence)) %>%
  print(n = Inf)

# Inspect model's most common topics
topic_by_model %>%
  group_by(Model) %>%
  slice_max(Mean_Prevalence, n = 5, with_ties = FALSE) %>%
  arrange(Model, desc(Mean_Prevalence)) %>%
  print(n = Inf)

# Show differences in models
topic_effects_MC <- estimateEffect(
  1:20 ~ Model + Exam + qtype + image,
  stm20,
  meta = meta
)

library(ggplot2)
ggplot(
  topic_by_model,
  aes(
    x = Topic_Label,
    y = Model,
    fill = Mean_Prevalence
  )
) +
  geom_tile() +
  scale_fill_viridis_c(
    name = "Mean\nprevalence",
    option = "C"
  ) +
  labs(
    x = "STM topic",
    y = "Model",
    title = "Mean STM topic prevalence by LLM"
  ) +
  theme_minimal(base_size = 11) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  )

ggsave(
  "figure_topic_prevalence_by_model.pdf",
  width = 10,
  height = 6
)

topic_by_model_z <- topic_by_model %>%
  group_by(Topic_Num) %>%
  mutate(
    Z_Prevalence = as.numeric(scale(Mean_Prevalence))
  ) %>%
  ungroup()

ggplot(
  topic_by_model_z,
  aes(
    x = Topic_Label,
    y = Model,
    fill = Z_Prevalence
  )
) +
  geom_tile() +
  scale_fill_gradient2(
    name = "Relative\nprevalence",
    low = "blue",
    mid = "white",
    high = "red",
    midpoint = 0
  ) +
  labs(
    x = "STM topic",
    y = "Model",
    title = "Relative topic prevalence by LLM"
  ) +
  theme_minimal(base_size = 11) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  )

ggsave(
  "figure_standardized_prevalence_by_model.pdf",
  width = 10,
  height = 6
)

####### Fit MC only STM 

stm_meta_MC <- stm_meta %>%
  filter(qtype == "MC")
nrow(stm_meta_MC)

mc_text <- stm_meta %>%
  filter(qtype == "MC")

processed_MC <- textProcessor(
  documents = mc_text$explanation_clean,
  metadata = mc_text
)

out_MC <- prepDocuments(
  processed_MC$documents,
  processed_MC$vocab,
  processed_MC$meta,
  lower.thresh = 5
)

docs_MC  <- out_MC$documents
vocab_MC <- out_MC$vocab
meta_MC  <- out_MC$meta

stm20_MC <- stm(
  documents = docs_MC,
  vocab = vocab_MC,
  K = 20,
  prevalence = ~ Model + Exam + image + MC_Response_Type,
  data = meta_MC,
  init.type = "Spectral"
)

topic_effects_MC <- estimateEffect(
  1:20 ~ Model + Exam + image + MC_Response_Type,
  stmobj = stm20_MC,
  metadata = meta_MC
)

theta_MC <- as.data.frame(stm20_MC$theta)
colnames(theta_MC) <- paste0("Topic_",1:20)

topic_response <- bind_cols(meta_MC, theta_MC) %>%
  group_by(MC_Response_Type) %>%
  summarise(
    across(starts_with("Topic_"), mean),
    .groups="drop"
  ) %>%
  pivot_longer(
    starts_with("Topic_"),
    names_to="Topic",
    values_to="Mean_Prevalence"
  ) %>%
  mutate(
    Topic_Num = as.integer(gsub("Topic_","",Topic)),
    Topic_Label = topic_labels_short[Topic_Num]
  )

ggplot(
  topic_response,
  aes(
    x = Topic_Label,
    y = MC_Response_Type,
    fill = Mean_Prevalence
  )
) +
  geom_tile() +
  scale_fill_viridis_c(option="C") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle=45,hjust=1)
  ) +
  labs(
    x="Reasoning Topic",
    y="Response Type",
    fill="Mean\nPrevalence"
  )

ggsave(
  "figure__prevalence_by_model_MConly.pdf",
  width = 10,
  height = 6
)

## The above plots do not reveal anything. Going with semantic similarity.


topic_response_z <-
  topic_response %>%
  group_by(Topic_Num) %>%
  mutate(
    Z = as.numeric(scale(Mean_Prevalence))
  )

saveRDS(stm_meta,              "stm_meta.rds")
saveRDS(stm20,                 "stm20.rds")
saveRDS(topic_labels,          "topic_labels.rds")
saveRDS(topic_labels_short,    "topic_labels_short.rds")
saveRDS(question_topics,       "question_topics.rds")

